#!/usr/bin/env ruby

Dir.glob('*.dot') do |file|
  dot_file = "." + File.basename(file, ".dot")
  `ln -s ~/.dotfiles/#{file} ~/#{dot_file}`
  puts "Linked file " + "#{dot_file}"
end

Dir.glob("config.fish") do |fish|
  `ln -s ~/.dotfiles/#{fish} ~/.config/fish/`
  puts "Linked file " + "#{fish}"
end

Dir.glob("nvim") do |nvim|
  `cp -R #{nvim} ~/.config/nvim`
  puts "Copied directory " "#{nvim}"
end

Dir.glob("init.vim") do |init|
  `cp -R #{init} ~/.config/nvim`
  puts "Linked file #{init}"
end
