#+TITLE: Amalthea
#+AUTHOR: Sondre Nilsen

* Introduction
This is my Emacs configuration, there are many like it but this one is mine.
It's decently personalized, but it should be useful for either inspiration or
just straight-up copy-pasta. My configuration is managed by [[https://github.com/emacscollective/borg][borg]], which is a
really nice and simple way of managing your Emacs packages by version.

At the moment I'm running Emacs from the latest revision of the master branch,
which means the version is 27.0, I'm using this because of the ~early-init.el~
file, but this configuration will work with versions below 27.0 too as it
concatenates the ~early-init.el~ file into the ~init.el~ file.

I've named my Emacs configuration ~Amalthea~, I have no recollection of why
anymore, other than the fact that I still think it's a cool name. It's named
after one of the minor moons of Jupiter.
* Installation
I am currently using [[https://github.com/emacscollective/borg][Borg]] to manage my dependencies, and as such installing and
trying out my configuration is very easy:

#+BEGIN_SRC shell
  git clone git@github.com:sondr3/amalthea.git ~/.emacs.d
  cd ~/.emacs.d/
  make bootstrap-borg
  make bootstrap
#+END_SRC

However, make sure you make a backup of your local configuration before doing
this as it'll completely overwrite whatever you have in your configuration. I
have also never actually attempted to bootstrap my editor again, so there's a
fair chance it'll go completely tits up, fair warning.
