#+TITLE: My dotfiles
#+AUTHOR: Sondre Nilsen
#+EMAIL: nilsen.sondre@gmail.com

#+BEGIN_QUOTE
These are my dotfiles, there are many like them but these ones are mine.

    -- Dotfiles Creed
#+END_QUOTE

* Applications
** Emacs
I'm currently running the latest stable release of Emacs, you find my
distribution of Emacs called Amalthea in the ~emacs~ directory or you can [[file:emacs/README.org][read the
README.]]
** Neovim
I'm really not using this at all besides very small and quick fixes to
configuration files, so my configuration is really out of date...
** Terminal
I run a small variety of terminals, at the moment my main terminal is Konsole
with Yakuake as a drop-down terminal.
* Usage
If you really want to use some of my configurations I recommend you instead look
at them and copy the sections that look helpful. I've configured my tools to my
liking and while I can answer some questions about the settings I will not help
with errors if you actually use them. /You have been warned./
