#+TITLE: X.Org settings
#+AUTHOR: Sondre Nilsen
#+EMAIL: nilsen.sondre@gmail.com

* Introduction
As mentioned elsewhere in my dotfiles I run bspwm and that uses the X.Org
display server to work, so we'll obviously have to configure that too.

* Initial configuration
Instead of having to manually start the display server whenever I log in I added
the following to ~/etc/profile~:

#+BEGIN_SRC shell :tangle no
  if [[ "$(tty)"=="/dev/tty1" ]]; then
    exec startx
  fi
#+END_SRC

This'll automatically start the server when you log in, which I do from the
console. Don't need no display manager.

* ~.xinitrc~
:PROPERTIES:
:header-args: :tangle ~/.xinitrc
:END:
This is the file that gets called when the server starts, and it's where I set
some initial settings and such to make sure everything works.

** Java
For some stupid reason Java/JVM hardcodes what Window Managers (WM) that it can
run under, so for bspwm you end up with tons of problems with Java applications,
like Intellij. So we'll have to fix that, obviously. There's two parts to this,
first settings a shell setting for Java and then using ~wmname~ to trick into
thinking it's a different WM than it actually is.

#+BEGIN_SRC shell
  export _JAVA_AWT_WM_NONREPARTENTING=1
#+END_SRC

** HiDPI
Then there's the issue with having a HiDPI display (2880x1800). I haven't tried
GNOME or KDE for this yet but at least bspwm doesn't do anything to properly set
it. So we'll have to configure QT and GTK for this.

#+BEGIN_SRC shell
  export QT_AUTO_SCREEN_SCALE_FACTOR=1
  export GDK_SCALE=1
  export GDK_DPI_SCALE=0.5
#+END_SRC

And then we'll have to set the DPI properly, because otherwise it's at 92 or
something silly that doesn't work.

#+BEGIN_SRC shell
  xrandr --dpi 220 &
#+END_SRC

** ~Xresources~
Now, we'll have to merge the settings for fonts and applications that rely on
their settings in ~~/.Xresources~.

#+BEGIN_SRC
  xrdb -merge ~/.Xresources &
#+END_SRC

** Keyboard layout and settings
I initially tried using ~localectl~ but it absolutely refused to pick up on the
keyboard settings that I set, so instead I'll have to do it with ~setxkbmap~. This
sets it so I have an English and Norwegian keyboard using the Mac layout, on a
MacBook Pro layout, and makes it so I can switch between it using ~ALT-SPC~ and
terminate my session with ~CTRL-ALT-BKSP~.

#+BEGIN_SRC shell
  setxkbmap "us(mac),no(mac)" -option "grp:alt_space_toggle,terminate:ctrl_alt_bksp" -model macbook79 &
#+END_SRC

** Compton
If you are unlucky like me you'll get a ton of screen tearing when browsing or
doing anything at all, and for this we'll use Compton to get rid of it. And with
it we can set shadows, fading and such awesome features.

#+BEGIN_SRC
  compton -b &
#+END_SRC

** Tricking Java
As mentioned above, we'll use ~wmname~ to trick Java into thinking we're using a
different WM than we're actually using.

#+BEGIN_SRC shell
  wmname LG3D &
#+END_SRC

** Hiding the cursor
There's a separate utility that was recommended on the Arch Wiki but it didn't
work, was old and a nasty hack. ~xbanish~ was recommended instead and it works
splendid. Note that it'll automatically hide the cursor when using the keyboard
or after a set time automatically, but just by moving it with my touchpad/mouse
it shows up again.

#+BEGIN_SRC shell
  xbanish &
#+END_SRC

** Setting the wallpaper
Initially I used ~feh~ to set the wallpaper, but switched to ~nitrogen~ for reasons.
No good reason really.

#+BEGIN_SRC shell
  nitrogen --restore &
#+END_SRC

** Night mode
I migrated from macOS and used ~Flux~ to make my eyes less tired through the day
by changing the color of the display as the day progresses. On Linux we have a
program called ~Redshift~ that does this just as well, it's awesome. Redshift's
settings are [[file:redshift.org][here]].

#+BEGIN_SRC shell
  redshift &
#+END_SRC

** Bars on top
For a macOS like bar on the top of my screen I'm using Polybar to configure it,
if you want to take a look at it's settings you can see them [[file:polybar.org][here]].

#+BEGIN_SRC shell
  polybar top &
#+END_SRC

** Keyboard shortcut daemon
If you're using bspwm, you're probably using ~sxhkd~ to manage your shortcuts and
all your keyboard needs. The configuration for it is located [[file:sxhkd.org][here]].

#+BEGIN_SRC shell
  sxhkd -m -1 &
#+END_SRC


** bspwm
And then finally we can start bspwm and finally use our computer! Huzzah.

#+BEGIN_SRC shell
  exec bspwm
#+END_SRC
* ~.Xresources~
:PROPERTIES:
:header-args: :tangle ~/.Xresources
:END:
This is where you configure various xorg-related utilities and programs that
rely on their settings from this or other files that are merged into ~xrdb~. We'll
only be configuring various settings for fonts, hinting and DPI etc.

#+BEGIN_SRC shell
  Xft.dpi: 220
  Xft.antialias: true
  Xft.hinting: true
  Xft.rgba: rgb
  Xft.autohint: false
  Xft.hintstyle: hintfull
  Xft.lcdfilter: lcddefault
#+END_SRC
