[alias]
t = "test -- --nocapture --color=always"
br = "build --release"
clip = "clippy -- -W clippy::pedantic"

{%- if is_linux() -%}
[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
{%- endif -%}

[net]
git-fetch-with-cli = true
