[alias]
t = "test --quiet -- --nocapture --color=always"
br = "build --release"
rr = "run --release"
pedantic = "clippy -- -W clippy::pedantic"
ped = "pedantic"
nursery = "clippy -- -W clippy::nursery"
nur = "nursery"

{%- if is_linux %}
[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
{%- endif %}

[net]
git-fetch-with-cli = true
