#+Title: Emacs configuration
#+Author: sondr3

* My Emacs settings
  This is my Emacs settings that are continuously evolving... and I'm a newbie so
  I don't really know what I'm doing either.

** NOTE
   This file is automatically tangled into a =emacs-init.el= file so no editing that file.

* Package management
  I have no idea how that works, but apparently [[https://github.com/rdallasgray/pallet][Pallet]] and [[https://github.com/cask/cask][Cask]] is the new
  hotness in Emacs-land. I will also be using the excellent [[https://github.com/jwiegley/use-package][use-package]] along
  with [[https://github.com/edvorg/req-package][req-package]] for some real package management goodness. Good golly.

* Core settings
  Some settings to give Emacs a bunch of sane defaults.

** =Req-package= (=use-package=) and custom settings
   Before we start using packages and such we need to setup =req-packages= and
   =use-package= as well

#+BEGIN_SRC emacs-lisp
  (require 'req-package)
  (setq custom-file "~/.emacs.d/custom.el")
  (load custom-file)
#+END_SRC

** Make sure the path loads properly on OS X
   This depends on the [[https://github.com/purcell/exec-path-from-shell][exec-path-from-shell]] package so it will properly load the
   path.

#+BEGIN_SRC emacs-lisp
  (req-package exec-path-from-shell
    :init
    (when (memq window-system '(mac ns))
    (exec-path-from-shell-initialize)))
#+END_SRC

** Encoding
   UTF-8 ALL THE THINGS!

#+BEGIN_SRC emacs-lisp
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)
#+END_SRC

** Some general settings
   Common sense settings really, most of these are pretty basic and shouldn't
   contain any magic. Most things are also comments just in case. 

*** Settings some defaults
#+BEGIN_SRC emacs-lisp
  (require 'uniquify)

  (setq
   x-select-enable-clipboard t                             ;; allow pasting outside Emacs
   global-auto-revert-non-file-buffers t                   ;; auto refresh dired quietly
   auto-revert-verbose nil
   echo-keystrokes 0.02                                    ;; show keystrokes in progress
   delete-by-moving-to-trash t                             ;; does what it says
   jump-char-lazy-highlight-face nil                       ;; don't highlight matches with jump-char
   line-number-mode t                                      ;; display line numbers
   column-number-mode t                                    ;; and columns
   fill-column 80                                          ;; lines should be 80 chars wide
   gc-cons-threshold 20000000                              ;; we have tons of memory now, don't be greedy
   enable-recursive-minibuffers t                          ;; let minibuffers be recursive
   visible-bell t                                          ;; hide that ding ding
   font-lock-maximum-decoration t                          ;; decorate all buffers with colors
   color-theme-is-global t                                 ;; does what it says
   truncate-partial-width-windows nil                      ;; truncate buffers
   tab-always-indent 'complete                             ;; tab before indenting
   require-final-newline t                                 ;; always add a newline when saving
   show-paren-delay 0                                      ;; because saving miliseconds is woreth it
   load-prefer-newer t                                     ;; prefer newer .el files to .elc
   window-combination-resize t                             ;; for better window resizing
   x-underline-at-descent-line t                           ;; draw underline lower
   uniquify-buffer-name-style 'post-forward-angle-brackets ;; make nonunique
                                                           ;; buffer names better
   uniquify-ignore-buffers-re "^\\*"                       ;; but don't mess with special buffersc'
   )

  (setq-default
   tab-width 4
   indent-tabs-mode nil                                     ;; indent with spaces and not tabs
   fill-column 80                                           ;; max 80 characters wide
   auto-fill-function 'do-auto-fill                         ;; automatically wrap long lines
   show-trailing-whitespace nil                             ;; whitespace mode
   )

  (global-auto-revert-mode 1)
  (electric-indent-mode)
#+END_SRC

*** Global modes
#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)    ;; show matching paranthesises
  (blink-cursor-mode -1) ;; don't blink the cursor
#+END_SRC

*** Save between sessions
    This makes it so when you open a file you've previously closed it'll open at
    the last location.

#+BEGIN_SRC emacs-lisp
  (req-package saveplace)
  (setq-default save-place t)
  (setq save-place-file (expand-file-name "places" user-emacs-directory))
#+END_SRC
*** Other
    Don't pause updating the display.

#+BEGIN_SRC emacs-lisp
(setq redisplay-dont-pause t)
#+END_SRC
** Annoying things
   Because nothing is perfect.

*** Lowercase/uppercase etc
    Mostly commands that annoy the hell out of me, like trying to undo and being
    asked repeadedly if you wanted to downcase it instead. Blerh.
#+BEGIN_SRC emacs-lisp
  (put 'downcase-region 'disabled nil)
  (put 'upcase-region 'disabled nil)
  (put 'narrow-to-region 'disabled nil)
  (put 'erase-buffer 'disable 'nil)
#+END_SRC

*** Autosaving and such
    Mostly because it's really annoying with all the =#filename= and =filename~=
    files that end up living in your directories.

#+BEGIN_SRC emacs-lisp
  (defvar backup-dir (expand-file-name "~/.emacs.d/backup/"))
  (defvar autosave-dir (expand-file-name "~/.emacs.d/autosave"))
  (setq backup-directory-alist (list (cons ".*" backup-dir)))
  (setq auto-save-list-file-prefix autosave-dir)
  (setq auto-save-file-name-transforms `((".*" ,autosave-dir t)))
  (setq backup-by-copying t)
#+END_SRC

*** Assorted annoyingness
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
  (setq x-select-enable-clipboard t)
  (setq vc-make-backup-files t)
#+END_SRC
** Keybindings
   Since I'm using the [[https://github.com/railwaycat/emacs-mac-port][emacs-mac-port]] of Emacs for OS X I need to change the
   keybindings for the meta key because it uses them backwards from what the
   normal settings are.

#+BEGIN_SRC emacs-lisp
  (setq mac-option-modifier 'meta)
  (setq mac-command-modifier 'super)
  (setq mac-pass-control-to-system nil)

  (global-set-key (kbd "s-q") 'save-buffers-kill-emacs)
  (global-set-key (kbd "s-v") 'yank)
  (global-set-key (kbd "s-c") 'copy-region-as-kill)
#+END_SRC
* Appearance
  Now comes the time to make sure Emacs starts looking dashin'.

** Bars, bars
   There's no need for the menubar/toolbar/scrollbar or splash screen so these are all hidden.

#+BEGIN_SRC emacs-lisp
  (if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
  (if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
  (if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
  (setq inhibit-startup-message t)
#+END_SRC

** Fonts
   I've currently settled for using Monaco for Emacs and terminals
   alike, it's a great font that's very easily readable and also works well with
   code and numbers.

#+BEGIN_SRC emacs-lisp
  (set-default-font "Monaco")
  (set-face-attribute 'default nil
                      :family "Monaco"
                      :height 120
                      :weight 'normal
                      :width 'normal)
#+END_SRC

** Theme
   Probably the most second most important thing in an editor for me, after of
   course a text editor. And an operating system. vim would be nice to have
   too. I've currently settled on using [[ethanschoonover.com/solarized][Solarized]] although it's not as pretty as
   I would've liked it to be. 

#+BEGIN_SRC emacs-lisp
  (req-package basic-theme)
#+END_SRC

*** Pretty mode
    Who doesn't like it pretty?

#+BEGIN_SRC emacs-lisp
  (req-package pretty-mode
    :config
    (global-pretty-mode 1))
#+END_SRC

** Powerline aka smart-mode-line
   After getting used to the pretty powerline in vim looking at the normal
   powerline in Emacs just isn't very nice, although it does show plenty of
   information. However, none of the direct vim forks of Powerline (or
   vim-airline in my case), so I ended up using [[https://github.com/Bruce-Connor/smart-mode-line/][smart-mode-line]] instead.

#+BEGIN_SRC emacs-lisp
  (req-package smart-mode-line
    :init
    (sml/setup)
    (setq sml/theme 'respectful))
#+END_SRC

*** Customizing the layout

#+BEGIN_SRC emacs-lisp
  (setq displa-time-day-and-date t
        display-time-format "%a %b %d %R"
        display-time-interval 60
        display-fime-default-load-average nil)
  (display-time)
#+END_SRC

** Gutter
   If you've used vim for a while you get used to having both relative line
   numbers as well as git diffs in the gutter. Personally I find this incredibly
   useful and so I'll be implementing it in Emacs as well.

*** Git-gutter
#+BEGIN_SRC emacs-lisp
  (req-package git-gutter
    :init
    (global-git-gutter-mode +1)
    :config
    (progn
      (git-gutter:linum-setup)))
#+END_SRC

*** Relative line numbers
#+BEGIN_SRC emacs-lisp
  (req-package linum-relative
    :init
    :config
    (progn
      (setq linum-relative-format "%3s ")
      (setq linum-relative-current-symbol "")
      (dolist (mode '(column-number-mode line-number-mode))
        (when (fboundp mode) (funcall mode t)))
      (dolist (mode-hook '(text-mode-hook prog-mode-hook conf-mode-hook))
        (add-hook mode-hook
                  (lambda ()
                    (linum-mode 1))))))
#+END_SRC

* EVIL aka vim in Emacs
  Now for the greater things in life; vim. As much as I love Emacs I still think
  modal editing is a much better way to edit text, and as such I'm using EVIL
  mode in Emacs to get all the goodies from vim into Emacs. It's a combination
  that simply can't be beat.

** =evil=

#+BEGIN_SRC emacs-lisp
  (req-package evil
    :require (evil-surround undo-tree ace-jump-mode)
    :ensure evil
    :init
    (progn
      (evil-mode 1)
      (setq evil-default-cursor t)
      (setq evil-motion-state-modes
            (append evil-emacs-state-modes evil-motion-state-modes))))
#+END_SRC

** =evil-leader=
   The leader is a really useful thing in Vim and pretty much required for me,
   and luckily with =evil-leader= you can have it in Emacs as well! Here it's
   set to =<SPACE>=.

#+BEGIN_SRC emacs-lisp
  (req-package evil-leader
    :require evil
    :ensure evil-leader
    :init
    (progn
      (evil-leader/set-leader "<SPC>")
      (global-evil-leader-mode 1)
      (evil-leader/set-key
        "w" 'ace-jump-word-mode
        "c" 'ace-jump-char-mode
        "l" 'ace-jump-line-mode)))
#+END_SRC
   
** =evil-surround=
   I love =vim-surround=, it's incredibly handy being able to switch what
   characters surround what, remove them, add new ones and so on and Tim Pope's
   plugin is great for it, luckily, it's for Emacs too.

#+BEGIN_SRC emacs-lisp
  (req-package evil-surround
    :init
    (global-evil-surround-mode 1))
#+END_SRC

** =undo-tree=
   Because the regular way that Emacs does undos is not very intuitive.

#+BEGIN_SRC emacs-lisp
  (req-package undo-tree
    :diminish ""
    :init
    (progn
      (setq undo-tree-auto-save-history t)
      (global-undo-tree-mode)))
#+END_SRC

** =ace-jump-mode=
   Getting around quickly is quite useful.

#+BEGIN_SRC emacs-lisp
(req-package ace-jump-mode)
#+END_SRC

** Keybinds
   The only one I really need is being able to use =jj= instead of =ESC=, but to
   do this I need [[http://www.emacswiki.org/emacs/key-chord.el][key-chord.el]].

#+BEGIN_SRC emacs-lisp
  (req-package key-chord
    :init
    (key-chord-mode 1)
    :config
    (progn
      (setq key-chord-two-keys-delay 0.5)
      (key-chord-define evil-insert-state-map "jj" 'evil-normal-state)))
#+END_SRC

* Editing
  Now that we have vim running inside of Emacs (almost), we really don't need
  much more. Well... maybe we do.

** Delimiters
   I like my paranthesises and brackets and whatnot to be matching and distinct,
   for this I use [[https://github.com/Fuco1/smartparens][smartparens]] and [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] for color matching
   them. Dashing.

   First some Emacs default settings.

#+BEGIN_SRC emacs-lisp
  (show-paren-mode t)
  (setq show-paren-delay 0)
  (setq show-paren-style 'parenthesis)

#+END_SRC

#+BEGIN_SRC emacs-lisp
  (req-package smartparens-config
    :ensure smartparens
    :diminish (smartparens-mode . "()")
    :init
    (smartparens-global-mode t)
    :config
    (progn
      (setq sp-show-pair-delay 0)
      (setq sp-show-pair-from-inside t)
      (setq sp-autoescape-string-quote nil)
      (setq sp-autoinsert-if-followed-by-same 1)
      (setq sp-highlight-pair-overlay nil)))

  (req-package rainbow-delimiters
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC 

   However we do need some colors elsewhere too.

#+BEGIN_SRC emacs-lisp
  (req-package rainbow-mode
    :diminish (rainbow-mode . "")
    :init
    (add-hook 'prog-mode-hook 'rainbow-mode))
#+END_SRC
** Magit
   It's literally magic.

#+BEGIN_SRC emacs-lisp
  (defvar magit-emacsclient-executable nil)
  (req-package magit
    :diminish magit-auto-revert-mode)
#+END_SRC

* Languages
  Now time to add some language specific configurations.

** Clojure

*** =clojure-mode=
   First of all, [[https://github.com/clojure-emacs/clojure-mode][clojure-mode]] for font-locking, indentations, navigation and
   such for Emacs.

#+BEGIN_SRC emacs-lisp
  (req-package clojure-mode)
  (req-package clojure-mode-extra-font-locking)

  (add-hook 'clojure-mode-hook 'smartparens-strict-mode)
  (add-hook 'clojure-mode-hook 'rainbow-delimiters-mode)
#+END_SRC

*** Cider
    And now to hook into the REPL for Clojure.

#+BEGIN_SRC emacs-lisp
  (req-package cider)

  (setq nrepel-log-messages
        nrepl-hide-special-buffers t
        cider-repl-tab-command 'indent-for-tab-command
        cider-prefer-local-resources t
        cider-repl-pop-to-buffer-on-connect nil
        cider-auto-select-error-buffer nil
        cider-stacktrace-fill-column 80
        nrepl-buffer-name-separator "-"
        cider-repl-result-prefix ";; =>"
        cider-interactive-eval-result-prefix ";; =>"
        )

  (add-hook cider-mode-hook 'cider-turn-on-eldoc-mode)
#+END_SRC
* And finish
  Now we only need to finish installing everything and we can be on our merry
  way!

#+BEGIN_SRC emacs-lisp
(req-package-finish)
#+END_SRC
