#+Title: Emacs configuration
#+Author: sondr3

* My Emacs settings
  This is my emacs settings that are continously evolving... and I'm a newbie so
  I don't really know what I'm doing either.

** NOTE
   This file is automagically tangled into a =emacs-init.el= file so no editing that file.

* Package management
  I have no idea how that works, but apparently [[https://github.com/rdallasgray/pallet][Pallet]] and [[https://github.com/cask/cask][Cask]] is the new
  hotness in Emacsland. I will also be using the excellent [[https://github.com/jwiegley/use-package][use-package]] along
  with [[https://github.com/edvorg/req-package][req-package]] for some real package management goodness. Good golly.

* Core settings

** Make sure the path loads properly on OS X
   This depends on the [[https://github.com/purcell/exec-path-from-shell][exec-path-from-shell]] package so it will properly load the
   path.

#+BEGIN_SRC emacs-lisp
  (when (memq window-system '(mac ns))
    (exec-path-from-shell-initialize))
#+END_SRC

** Encoding
   UTF-8 ALL THE THINGS!

#+BEGIN_SRC emacs-lisp
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-language-environment "UTF-8")
  (prefer-coding-system 'utf-8)
#+END_SRC

** Some general settings
   Common sense settings really, most of these are pretty basic and shouldn't
   contain any magic. Most things are also comments just in case. 

#+BEGIN_SRC emacs-lisp
  (setq
   x-select-enable-clipboard t           ;; allow pasting outside Emacs
   global-auto-revert-non-file-buffers t ;; auto refresh dired quietly
   auto-revert-verbose nil
   echo-keystrokes 0.1                   ;; show keystrokes in progress
   delete-by-moving-to-trash t           ;; does what it says
   jump-char-lazy-highlight-face nil     ;; don't highlight matches with jump-char
   line-number-mode t                    ;; display line numbers
   column-number-mode t                  ;; and columns
   fill-column 80                        ;; lines should be 80 chars wide
   gc-cons-threshold 20000000            ;; we have tons of memory now, don't be greedy
   enable-recursive-minibuffers t        ;; let minibuffers be recursive
   visible-bell t                        ;; hide that ding ding
   font-lock-maximum-decoration t        ;; decorate all buffers with colors
   color-theme-is-global t               ;; does what it says
   truncate-partial-width-windows nil    ;; truncate buffers
   )

  (setq-default
   tab-width 4
   indent-tabs-mode nil                  ;; indent with spaces and not tabs
   fill-column 80
   )
#+END_SRC

* Appearance
  Now comes the time to make sure Emacs starts looking dashin'. These settings configure (in order)

** Bars, bars
   There's no need for the menubar/toolbar/scrollbar or splash screen so these are all hidden.

#+BEGIN_SRC emacs-lisp
  (if (fboundp 'menu-bar-mode) (menu-bar-mode -1))
  (if (fboundp 'tool-bar-mode) (tool-bar-mode -1))
  (if (fboundp 'scroll-bar-mode) (scroll-bar-mode -1))
  (setq inhibit-startup-message t)
#+END_SRC
