#+TITLE: Configuring Emacs
#+AUTHOR: Sondre Nilsen
#+EMAIL: nilsen.sondre@gmail.com

* Preface

I've always been a fan of ~org-babel~, even from before I used
Emacs. Now I can finally document the whys and hows without tons of
comments everywhere.

** Setup 

I run the latest and greatest of Emacs (whatever that is) under OS X.

* General settings
For settings that don't really belong in any specific category.

*** Name
#+BEGIN_SRC emacs-lisp :tangle yes
  (setq user-full-name "Sondre Nilsen"
        user-mail-addres "nilsen.sondre@gmail.com")
#+END_SRC

*** Packages
Load Marmalade and Melpa for more packaging goodness.
#+BEGIN_SRC emacs-lisp :tangle yes
  (require 'package)
  (add-to-list 'package-archives
               '("melpa" . "http://melpa.org/packages/")
               '("marmalade" . "http://marmalade-repo.org/packages/"))
  (package-initialize)
#+END_SRC

And since I am going to be using ~use-package~ for installing and
configuring packages as well, I need to make sure that is installed as
well.
#+BEGIN_SRC emacs-lisp :tangle yes
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))
  (require 'use-package)
#+END_SRC

Furthermore, I want to automatically compile my emacs files.
#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package auto-compile
    :ensure t
    :config (auto-compile-on-load-mode))
  (setq load-prefer-newer t)
#+END_SRC

* Interface
** Font
Good fonts are important and I normally change quite often between
some, but have now settled for Source Code Pro. It has all the bells
and whistles that I want and looks really good.
#+BEGIN_SRC emacs-lisp :tangle yes
  (set-frame-font "Source Code Pro")
  (set-face-attribute 'default nil
                      :height 120)
#+END_SRC
** Real estate
I don't need any of these as they just end up taking up my precious screen real estate.
#+BEGIN_SRC emacs-lisp :tangle yes
  (when window-system
    (tooltip-mode -1)
    (tool-bar-mode -1)
    (menu-bar-mode 1)
    (scroll-bar-mode -1))
#+END_SRC

** Cursor
I have a hard time with using a box for the cursor compared to a bar,
since I never seem to figure out which side of the character the
cursor is on. So we change the cursor to be a bar instead.
#+BEGIN_SRC emacs-lisp :tangle yes
  (setq-default cursor-type 'bar)
#+END_SRC
** Window title
I'd like to be able to see which file I'm editing from the frame, not
just ~Emacs@hostname~. 
#+BEGIN_SRC emacs-lisp :tangle yes
  (setq frame-title-format '(:eval (concat (buffer-name) " :: GNU Emacs")))
#+END_SRC
* Evil
** Installing
I won't claim that I'm a huge VIM power user, because I'm not, but
after having used it for a while (and only scratching the surface), I
absolutely cannot live without it. So by extension I need Evil in
Emacs for some lovely VIM on Emacs action.
#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package evil
    :ensure t
    :init
    (evil-mode 1))
#+END_SRC
** Leader and chords 
I switched the leader key in VIM to ~<SPC>~ almost immediately after
starting to use it, so I don't even know what it is set to by
default. So I need it to be space here too.

I also have a few chords set up that I use for various commands:
| Command                | Chord     |
|------------------------+-----------|
| Save current buffer    | ~<SPC> w~ |
| Open file              | ~<SPC> o~ |
| Switch between buffers | ~<SPC> b~ |

I also set up a few chords that I use for various things, currently I
only really need to use is ~<SPC> w~ to save my current buffer.
#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package general
    :ensure t
    :config
    (progn
      (setq general-default-keymaps 'evil-normal-state-map)
      (setq general-default-prefix "<SPC>")
      (general-define-key "w" 'save-buffer
                          "o" 'find-file
                          "b" 'switch-to-buffer)))
#+END_SRC
** Using ~jk~ to exit insert mode
~ESC~ is just too far to reach for mere mortals, and I even play
piano. So I changed the way you exit Insert Mode in VIM to be ~jk~ to
help my pinky. For this we have to use a package called ~KeyChord~.
#+BEGIN_SRC emacs-lisp :tangle yes
  (use-package key-chord
    :ensure t
    :config
    (setq key-chord-two-keys-delays 0.5)
    (key-chord-define evil-insert-state-map "jk" 'evil-normal-state)
    (key-chord-mode 1))
#+END_SRC
** Keybinds
*** Change ~:~ to ~;~
I read about this on reddit while I still used VIM and I really
enjoyed it. It also helps that I'm lazy and don't want to press ~S-:~.
#+BEGIN_SRC emacs-lisp :tangle yes
  (define-key evil-normal-state-map (kbd ";") 'evil-ex)
#+END_SRC
*** Moving between buffers
I use Tmux in my terminal and bound the key to switch between windows
in it to be ~C-[hjkl]~, and did the same in VIM to be able to move
between windows in both Tmux and VIM. So to have the same in Emacs
would be nice, even though I could use ~C-w [hjkl]~.
#+BEGIN_SRC emacs-lisp :tangle yes
  (define-key evil-normal-state-map (kbd "C-h") 'evil-window-left)
  (define-key evil-normal-state-map (kbd "C-j") 'evil-window-down)
  (define-key evil-normal-state-map (kbd "C-k") 'evil-window-up)
  (define-key evil-normal-state-map (kbd "C-l") 'evil-window-right)
#+END_SRC
* Functions
** Automatically tangle and byte compile init.org
I tried having a local variable at the end of this file that would automatically
tangle this file into a ~init.el~ file on save, but that didn't work so I had to
steal this function instead. It also byte compiles the ~init.el~ file on save as 
well. Taken from [[https://github.com/larstvei/dot-emacs]].

Due to how I organize my dotfiles, Emacs will ask to follow the
symlink to where I link it from, this is not wanted behaviour as it
makes the function not work since you're no longer editing a file in
your emacs home directory.  
#+BEGIN_SRC emacs-lisp :tangle yes
  (defun my/tangle-init()
    "If the current file is 'init.org', the code blocks are tangled and compiled"
    (when (equal (buffer-file-name)
                 (expand-file-name (concat user-emacs-directory "init.org")))
      (let ((prog-mode-hook nil))
        (org-babel-tangle)
        (byte-compile-file (concat user-emacs-directory "init.el")))))

  (add-hook 'after-save-hook 'my/tangle-init)
#+END_SRC
