require("plugins.gitsigns")
require("plugins.tree-sitter")
require("plugins.mini")
require("plugins.which-key")
require("plugins.fzf")
require("plugins.surround")
require("plugins.hlchunk")
require("plugins.barbar")
require("plugins.yazi")
require("plugins.neotree")
require("plugins.tiny")

require("plugins.language.rust")
require("plugins.language.haskell")

require("plugins.lsp")
require("plugins.cmp")
require("plugins.neotest")
require("plugins.trouble")
