#!/usr/bin/env bash

# Ask for sudo
sudo -v

# Upgrade and update
brew update
brew upgrade --all

# Install cask
brew install caskroom/cask/brew-cask

# Tap some brews
brew tap neovim/neovim
brew tap mpv-player/mpv

# Install fish for command line omgz
brew install fish
brew install zsh

# Install packages you want
brew install git --with-brewed-openssl
brew install tmux --HEAD
brew install reattach-to-user-namespace
brew install --HEAD neovim
brew install tree
brew install --HEAD mpv

# Install programming stuff
brew install ruby --with-doc
brew install nodejs --without-npm
echo prefix=~/.node >> ~/.npmrc
curl -L https://www.npmjs.com/install.sh | sh

# Install Apps
brew cask install google-chrome
brew cask install firefox
brew cask install vlc
brew cask install deluge
brew cask install garmin-express
brew cask install mailbox
brew cask install dropbox
brew cask install rescuetime
brew cask install spotify
brew cask install launchbar
brew cask install skype
brew cask install steam
brew cask install air-video-server-hd

# And clean
brew cleanup
