#+TITLE: Amalthea
#+AUTHOR: Sondre Nilsen

* Introduction
Throughout the eons, there have been many Emacs configurations, but this one is
mine. I've been on a long journey from copy-pasting random snippets off of Stack
Overflow, to attempting my own configurations, to [[http://spacemacs.org/][Spacemacs]], back again to my
own [[https://github.com/sondr3/dotfiles/blob/master/emacs.org][Org mode powered configuration]] and finally back to this... [[https://en.wikipedia.org/wiki/Amalthea_(moon)][Amalthea!]]

I'm a big fan of the [[https://en.wikipedia.org/wiki/KISS_principle][KISS principle]], though calling Emacs simple might be
stretching it a little. This configuration tries to stay clean and simple, there
are no crazy macro or function shenanigans and I try to make sure everything is
well documented.

For a rough overview over how this configuration works, it is configured into
three (well, four) separate "layers". The ~core~ layer is where packages and
configuration that everything else relies on is, package management, key
bindings and configuration of the core of Amalthea. The ~base~ layer is
essentially what makes my configuration into what it is, here is [[https://github.com/emacs-evil/evil][Evil]], [[https://github.com/company-mode/company-mode][Company]],
[[https://github.com/bbatsov/projectile][Projectile]], [[https://github.com/abo-abo/swiper][Ivy]] and more is configured. Second to last, the ~modules~ layer is
where configuration for specific modes resides, Org mode, LaTeX, Haskell and so
on. Finally, the ~utils~ layer contains... utilities.

The biggest difference is that these layers are baked into my ~init.el~ file,
which I'm editing using a [[https://github.com/alphapapa/outshine][outshine]], so I can move around the file as if I'm
editing a Org-mode document.

As an addendum, for those who wonder why I named my Emacs Amalthea... I have no
recollection of why anymore, other than the fact that I still think it's a cool
name. It's named after one of the minor moons of Jupiter.
* Installation
Don't, it'll only end in pain. Take what you want from my configuration instead.
* Inspiration
At the moment I'm running Emacs from the latest revision of the master branch,
which means the version is 27.0, I'm using this because of the ~early-init.el~
file, but this configuration will work with versions 26 and above too as it
concatenates the ~early-init.el~ file into the ~init.el~ file.

To configure Emacs and the packages I require I am currently using [[https://nixos.org/nix/][Nix]] to list
and automatically install everything. You can see my ~emacs.nix~ file [[https://github.com/sondr3/dotfiles/blob/master/emacs.nix][here]]. As
such, there is no way to install the packages I use from inside Emacs.

But feel free to copy and take whatever parts of the configuration you want to
try out.
