name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: formatting
        uses: JohnnyMorganz/stylua-action@v1.1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
