name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Build
        run: deno compile --lock lock.json --unstable --import-map import_map.json -A -o dots main.ts

      - name: Test
        run: deno test --unstable --import-map import_map.json -A
